### ISSUE TITLE
Build fail when I use the libray with next js

### ISSUE THREAD

**Issue by igeral** [williamiommi/sanity-plugin-i18n-fields#3]
Hi guys I am using the plugin with nextjs but each time I deploy to vercel I get the following error 

./node_modules/keen-slider/keen-slider.min.css
--
20:12:35.197 | Module build failed: Error: Final loader (./node_modules/next/dist/build/webpack/loaders/error-loader.js) didn't return a Buffer or String
20:12:35.197 | at processResult (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:398849)
20:12:35.197 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:400319
20:12:35.197 | at /vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8727
20:12:35.197 | at iterateNormalLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5565)
20:12:35.197 | at iterateNormalLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5650)
20:12:35.197 | at /vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5879
20:12:35.197 | at runSyncOrAsync (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4185)
20:12:35.197 | at iterateNormalLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5782)
20:12:35.197 | at /vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5426
20:12:35.197 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:399794

**Comment by williamiommi** [comment]
Hi,

I installed the plugin on my Next.js project, and the deployment on Vercel was successful. Are you also using Keen Slider within your project? Can you share your setup?

When Googling the error "Error: Final loader didn't return a Buffer or String," I mainly find references to the 'awesome-typescript-loader' package. Are you using it?
